
<!-- 
<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

<table class="table table-striped table-bordered" style="margin:20px;width:600px;">
  <tr>
  <th>DB NAME</th>
    <th>DMMS DATE</th>
    <th>METRIC ID</th>
    <th>METRIC VALUES</th>
    
  </tr>
  <?php $i = 0;?>
  <?php foreach ($this->monitorresults as $entrys): ?>
  	
  	<?php foreach ($entrys as $entry)   :?>
  	
  <tr>
    
    <td><?php echo $this->dbnames[$i] ?>
    <?php foreach ($entry as $row) :?>
    
    <td><?php echo $row ?></td>
    <?php endforeach;?>
    
  </tr>
    
  	<?php endforeach ?>
  	<?php $i++; ?>
  	
 <?php endforeach ?>
 	
   
</table>
-->

 
<?php $count = 0;
$DBconunt = 0;
//require 'Function/Tools.php';
?>
<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
<?php foreach ($this->monitorresults as $entrys): ?>
	

<table id= "test" class="table table-striped table-bordered" style="margin:20px;width:600px;">
  <tr>   
    <th>DMMS DATE</th>
    <th>MDES</th>
    <th>MDLH</th>
    <th>MDMG</th>
    <th>MDSC</th>
    <th>MDTC</th>
    <th>MDTV</th>
    <th>MDVC</th>
    <th>MDVT</th>
   

  
  		<?php $temp_date = 'init';
 			  $count = 0;
 			 
 		?>
	  	<?php foreach ($entrys as $entry)   :?>
		  	<?php 
		     
		  	
			  	if ($temp_date <> $entry['DMMS_DATE'])
			  	{
			  		if ($count <> 0 && $count <> 8) 
			  		{
			  			for ($i=0;$i<(8-$count);$i++)
			  			{
			  				echo '<td style="background:yellow; " >'.'NULL'.'</td>';
			  			}
			  			echo '</tr>';
			  		}
			  		echo '<tr>';
			  		
			  		echo '<td>'.$entry['DMMS_DATE'].'</td>';
			  		$count=0;
			  	}
			  	
			  	
			    $temp_date=$entry['DMMS_DATE'];
			    
			    $flag = 1;
			   
			    while ($flag)
			    {
			    	
				    if ($count == 0)
				    {
				    	if($entry['METRIC_ID'] == 'MDES')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDES']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else 
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		
				    		
				    	}
				    }
				    
				    if ($count == 1)
				    {
				    	if($entry['METRIC_ID'] == 'MDLH')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDLH']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		 
				    	}
				    }
				    if ($count == 2)
				    {
				    	if($entry['METRIC_ID'] == 'MDMG')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDMG']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    
				    	}
				    }
				    
				    if ($count == 3)
				    {
				    	if($entry['METRIC_ID'] == 'MDSC')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDSC']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		 
				    	}
				    }
				    if ($count == 4)
				    {
				    	if($entry['METRIC_ID'] == 'MDTC')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDTC']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		 
				    	}
				    }
				    if ($count == 5)
				    {
				    	if($entry['METRIC_ID'] == 'MDTV')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDTV']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		 
				    	}
				    }
				    if ($count == 6)
				    {
				    	if($entry['METRIC_ID'] == 'MDVC')
				    	{
				    		
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDVC']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			break;
				    			}
				    			else 
				    			{
				    			
						    		echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
						    		$count++;
						    		break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			break;
				    			
				    		}
				    	}
				    	else
				    	{
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		 
				    	}
				    }
				    if ($count == 7)
				    {
				    	
				    	if($entry['METRIC_ID'] == 'MDVT')
				    	{
				    		if(array_key_exists($DBconunt,$this->avgvalues) && !Function_Tools::IsWeekend($temp_date))
				    		{
				    			if (Function_Tools::IsAccept($entry['SUMVALUE'], $this->avgvalues[$DBconunt]['MDVT']))
				    			{
				    				echo '<td>'.$entry['SUMVALUE'].'</td>';
					    			$count++;
					    			echo '</tr>';
					    			break;
				    			}
				    			else
				    			{
				    				 
				    				echo '<td style="background:red;">'.$entry['SUMVALUE'].'</td>';
				    				$count++;
				    				echo '</tr>';
				    				break;
				    			}
				    		}
				    		else 
				    		{
				    			echo '<td>'.$entry['SUMVALUE'].'</td>';
				    			$count++;
				    			echo '</tr>';
				    			break;
				    			
				    		}
				    		
				    	}
				    	else
				    	{
				    		
				    		echo '<td style="background:yellow; " >'.'NULL'.'</td>';
				    		$count++;
				    		break;	 
				    	}
				    }
			    }
		
		  	
		  	?>
		  	
  		<?php endforeach;?>
  		<?php 
  		
		  		if ($count <> 0) 
			  		{
			  			for ($i=0;$i<(8-$count);$i++)
			  			{
			  				echo '<td style="background:yellow; " >'.'NULL'.'</td>';
			  			}
			  			echo '</tr>';
			  		}
		?>
  </table>
  
 <?php $DBconunt++;?>

<?php endforeach;?>



