<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: 'Job Historical Ran Information',
                x: -20 //center
            },
            subtitle: {
                text: 'Check the Last Run Time and Job Status',
                x: -20
            },
            xAxis: {
                categories: [<?php 
                $i = 1;
                foreach ($this->jobrunresult as $item)
                {
  	
                	echo "'".$item['LASTRUNTIME']."'";
                	
                	if ($i != $this->jobrunresult->count())
                	 {
                		echo ",";
                	 }
                	 $i ++;
				}				
				?>]
            },
            yAxis: {
                title: {
                    text: 'Job Status'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: ' (STATUE CODE) '
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: <?php 
                foreach ($this->jobrunresult as $item)
                {                	 
                	echo "\"".$item['JOBNAME']."\"";    	 
                 	BREAK;
                } 
                
                ?>,
                data: [<?php 
                $i = 1;
                foreach ($this->jobrunresult as $item)
                {
                	//strpos()  substr() strrpos()
                	
                	$startpos = strpos($item['JOBSTATUS'], '(') ;
                	$endpos = strrpos($item['JOBSTATUS'], ')');
                	$length = $endpos - $startpos ;
                	$jobstatus = substr($item['JOBSTATUS'], $startpos + 1,$length - 1);
                	
                	echo $jobstatus;
                	
                	if ($i != $this->jobrunresult->count())
                	{
                		echo ",";
                	}
                	$i ++;
				}				
				?>]
            }]
        });
    });
    

		</script>
<body>
<script type="text/javascript" src="/js/highcharts.js"></script>
<script type="text/javascript" src="/js/exporting.js"></script>
<div id="container" style="min-width: 200px; height: 300px; margin: 20px,100px,100px,100px "></div>

<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
<div>
	<div id="table_left" style="float:left;width:50%;">
		<table class="table table-striped table-bordered" style="margin:20px;width:600px;"> 
	 
	        
	            <tr>
	            <td>HOST NAME</td>
	            <td>PROJECT NAME</td>
	            <td>JOB NAME</td>
	            <td>JOB STATUS</td>
	            <td>LAST RUN TIME</td>
	   
	            
	            </tr>
	     <?php foreach ($this->jobrunresult as $monitorresult) : ?>
	      
	            <tr>
	            <td><?php echo $monitorresult['HOSTNAME'] ?></td>
	            <td><?php echo $monitorresult['PROJECTNAME'] ?></td>
	            <td><?php echo $monitorresult['JOBNAME'] ?></td>            
	            <td><?php echo $monitorresult['JOBSTATUS'] ?></td>
	            <td><?php echo $monitorresult['LASTRUNTIME'] ?></td>
	            </tr>
	
	    <?php endforeach ?>
	 </table>
  </div>   
  <div id="scheduleinfo" style="float:left;width:50%;">
     <div style="margin:0 auto;text-align:center;">
     <?php 
     $scheduleinfo = explode(';',$this->scheduletime);
     ?>
     <table id = "schedule_list" class="table table-striped table-bordered" style="margin:20px;width:600px;"> 
     <tr>
     <td>SCHEDULE TIME</td>
     <td>OPTION</td>
     <?php 
     
    	$this->form->setAction($this->url());
     	foreach ($scheduleinfo as $item)
     	{
     		if ($item != NULL)
     		{    	
	     		echo "<tr>";
	     		echo "<td>".Function_Tools::DisplayCrontabTime($item)."</td>";
	     		echo "<td>"."DELETE"."</td>";
	     		echo "</tr>";
     		}
     	}
     	
     	
     	echo $this->form;
     ?>
     
     </tr>
     </table>
     </div>
  </div>
</div>
 
</body>