<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en_US">
<head>
  <meta name="generator" content="HTML Tidy for HTML5 (experimental) for Windows https://github.com/w3c/tidy-html5/tree/c63cc39" />
  <link href="/style.css" rel="stylesheet" type="text/css" />

  <title>Welcome</title>
  <script type="text/javascript" src="/js/menucontrol.js"></script>
  <script src="/js/jquery-2.1.0.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="/js/GetJobList.js"></script>

</head>

<body>
  <div id="header">
    <img id="logo" title="Centreon Logo" src="/Images/centreon.png" />

    <div id="resume_light">
	<?php echo $this->render('overview.phtml') ?>
	</div><span id="linkBar"></span><span id="logli"><img alt="Documentation" src=
    "/Images/help.png" /><a title="Documentation" href="http:www.baidu.com">Documentation</a> - You are <a href=
    "http:www.baidu.com">user-database</a><a title="Centreon - IT and Network Monitoring" href="#" onclick=
    "return false;"><img title="Please define autologin authentication key in your profile." src=
    "/Images/lock_preferences.png" /></a><a href="index.php?disconnect=1"><img alt="Logout" src="/Images/logout.png" /></a><a href=
    "http:www.baidu.com">LOG OUT</a></span>

    <div id="date">
      2014/04/25 7:14
    </div>

    <div id="centreonMsg"></div>

    <div id="debug"></div>
  </div>

  <div id="forMenuAjax">
    <div id="menu1_bgcolor">
      <div id="menu_1">
        <ul>
          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="http://etl_monitor.zf/monitorpage/monitorresult">Home</a>
            </div>
          </li>

          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="http://etl_monitor.zf/monitorpage/monitorresult">Monitoring</a>
            </div>
          </li>

          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="http://etl_monitor.zf/configpage/hostinfo">Administration</a>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <div id="menu_2">
      <div id="menu2_bgcolor">
        <div class="submenu"></div>

        <div class="submenu"></div>

        <div class="submenu">
          <span class="span2"><a style="white-space:nowrap;" href="http://etl_monitor.zf/configpage/hostinfo">Hosts</a></span>
          <span class="separator_menu2">|</span> <span class="span2"><a style="white-space:nowrap;" href=
          "http://etl_monitor.zf/configpage/monitoringjobinfo">Jobs</a></span>
        </div>
      </div>
    </div>
  </div>

  <div id="contener">
    <?php echo $this->layout()->content  ?>
  </div>
</body>
</html>

