<?php echo $this->doctype() ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en_US">
<head>
  <link href="/style.css" rel="stylesheet" type="text/css"/>
  <script src="/js/jquery-2.1.0.min.js"></script>
  <script type="text/javascript" src="/js/GetJobList.js"></script>
  <title>Welcome</title>
</head>

<body>
  <div id="header">
    <img id="logo" title="Centreon Logo" src="/Images/centreon.png" />

    <div id="resume_light">
      <table border="0" cellspacing="0" cellpadding="0">
        <tbody>
          <tr>
            <td>
              <table class="Resume_light_table">
                <tbody>
                  <tr class="Resume_light_header" style="white-space:nowrap;">
                    <td>Hosts</td>

                    <td>Up</td>

                    <td>Down</td>

                    <td>Unreachable</td>

                    <td>Pending</td>
                  </tr>

                  <tr>
                    <td>
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">5</a>
                      </div>
                    </td>

                    <td style="background:#19EE11">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">5</a>
                      </div>
                    </td>

                    <td style="background:#F91E05">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">0</a>
                      </div>
                    </td>

                    <td style="background:#82CFD8">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">0</a>
                      </div>
                    </td>

                    <td style="background:#82CFD8">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">0</a>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td></td>

            <td>
              <table class="Resume_light_table">
                <tbody>
                  <tr class="Resume_light_header" style="white-space:nowrap;">
                    <td>Services</td>

                    <td>Ok</td>

                    <td>Warning</td>

                    <td>Critical</td>

                    <td>Unknown</td>

                    <td>Pending</td>
                  </tr>

                  <tr>
                    <td>
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">116</a>
                      </div>
                    </td>

                    <td style="background:#19EE11">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">100</a>
                      </div>
                    </td>

                    <td style="background:#F8C706">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">7/9</a>
                      </div>
                    </td>

                    <td style="background:#F91E05">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">2/6</a>
                      </div>
                    </td>

                    <td>
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">1/1</a>
                      </div>
                    </td>

                    <td style="background:#82CFD8">
                      <div id="hosts" style="background:white;text-align:center">
                        <a href="main.php?p=20102&amp;o=h&amp;search=">0</a>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </div><span id="linkBar"></span><span id="logli"><img alt="Documentation" src="/Images/help.png" /><a title="Documentation"
    href="http:www.baidu.com">Documentation</a> - You are <a href="http:www.baidu.com">user-database</a><a title=
    "Centreon - IT and Network Monitoring" href="#" onclick="return false;"><img title=
    "Please define autologin authentication key in your profile." src="/Images/lock_preferences.png" /></a><a href=
    "index.php?disconnect=1"><img alt="Logout" src="/Images/logout.png" /></a><a href="http:www.baidu.com">LOG OUT</a></span>

    <div id="date">
      2014/04/25 7:14
    </div>

    <div id="centreonMsg"></div>

    <div id="debug"></div>
  </div>

  <div id="forMenuAjax">
    <div id="menu1_bgcolor">
      <div id="menu_1">
        <ul>
          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="">Home</a>
            </div>
          </li>

          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="http://etl_monitor.zf/monitorpage/monitorresult">Monitoring</a>
            </div>
          </li>

          <li>
            <div class="menu">
              <a onclick="loadAjax(1); return false;" href="">Administration</a>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <div id="menu_2">
      <div id="menu2_bgcolor">
        <span class="span2"><a style="white-space:nowrap;" href="http://etl_monitor.zf/configpage/hostinfo">Hosts</a></span>
        <span class="separator_menu2">|</span> <span class="span2"><a style="white-space:nowrap;" href=
        "http://etl_monitor.zf/configpage/monitoringjobinfo">Jobs</a></span>
      </div>
    </div>
  </div>

  <div id="contener">
   <?php echo $this->layout()->content  ?>
  </div>
</body>
</html>

