
          <table border="0" cellspacing="0" cellpadding="0">
            <tbody>
              <tr>
                <td>
                  <table class="Resume_light_table">
                    <tbody>
                      <tr class="Resume_light_header" style="white-space:nowrap;">
                        <td>Services</td>

                        <td>Ok</td>

                        <td>Warning</td>

                        <td>Critical</td>

                        <td>Unknown</td>

                      </tr>

                      <tr>
                        <td>
                          <div id="service_total" style="background:white;text-align:center">
                           <?php echo $this->overviewresults[4] ?>
                          </div>
                        </td>

                        <td style="background:#13EB3A">
                          <div id="service_ok" style="background:white;text-align:center">
                            <?php echo $this->overviewresults[0] ?>
                          </div>
                        </td>

                        <td style="background:#F8C706">
                          <div id="service_warning" style="background:white;text-align:center">
                            <?php echo $this->overviewresults[1] ?>
                          </div>
                        </td>

                        <td style="background:#F91D05">
                          <div id="service_critical" style="background:white;text-align:center">
                            <?php echo $this->overviewresults[2] ?>
                          </div>
                        </td>

                        <td style="background:#DCDADA">
                          <div id="service_unknown" style="background:white;text-align:center">
                            <?php echo $this->overviewresults[3] ?>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
 